on:
  workflow_dispatch:
  push:
    tags:
      - 'api-[v]\d+.\d+.\d+'
      - 'api-\d+.\d+.\d+'
name: Push server image to ECR

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    name: Deploy server
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: api_repo
          IMAGE_TAG: latest
        run: |
          npm run build:api
          docker tag skryba-api:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

