on:
  workflow_dispatch:
  push:
    tags:
      - 'client-[v]\d+.\d+.\d+'
      - 'client-\d+.\d+.\d+'
name: Publish client on AWS

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Setup npm
        run: npm install -g npm@7

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Create .env file
        run: |
          cd apps/skryba
          touch .env
          echo NX_API_URL=https://api.skryba.link/ >> .env
          cd ../..

      - name: Build client
        run: npx nx build skryba --prod

      - name: Publish
        uses: reggionick/s3-deploy@v3
        with:
          folder: dist/apps/skryba
          bucket: ${{ secrets.S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_ID }}
