on:
  workflow_dispatch:
  push:
    tags:
      - 'client-[v]\d+.\d+.\d+'
      - 'client-\d+.\d+.\d+'
name: Publish client on AWS

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Setup npm
        run: npm install -g npm@7

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Create .env file
        run: |
          cd apps/skryba
          touch .env
          echo NX_API_URL=https://api.skryba.link/ >> .env
          cd ../..

      - name: Build client
        run: npm run build

      - name: Publish
        uses: reggionick/s3-deploy@v3
        with:
          folder: dist/apps/skryba
          bucket: ${{ secrets.S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_ID }}
          bucket-region: eu-west-1
